spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.174.54.139:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

